"""create imoveis table

Revision ID: 73c362d9dbec
Revises: 
Create Date: 2025-11-29 13:18:22.875089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '73c362d9dbec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imoveis',
    sa.Column('apelido_imovel', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('endereco', sqlmodel.sql.sqltypes.AutoString(length=600), nullable=False),
    sa.Column('valor_aluguel_base', sa.Float(), nullable=False),
    sa.Column('tipo_imovel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_proprietario', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imoveis')
    # ### end Alembic commands ###
