"""Setup inicial

Revision ID: 9c019ab54f60
Revises: 34a3649b2f8e
Create Date: 2025-11-29 23:28:29.573306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9c019ab54f60'
down_revision: Union[str, None] = '34a3649b2f8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inquilinos', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('endereco_anterior',
               existing_type=sa.VARCHAR(length=600),
               nullable=False)
        batch_op.alter_column('renda_mensal',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inquilinos', schema=None) as batch_op:
        batch_op.alter_column('renda_mensal',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('endereco_anterior',
               existing_type=sa.VARCHAR(length=600),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
