"""add proprietario inquilino and contrato tables

Revision ID: 34a3649b2f8e
Revises: f8aec2a60475
Create Date: 2025-11-29 15:48:17.553361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '34a3649b2f8e'
down_revision: Union[str, None] = 'f8aec2a60475'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inquilinos',
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('cpf', sqlmodel.sql.sqltypes.AutoString(length=14), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('telefone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('endereco_anterior', sqlmodel.sql.sqltypes.AutoString(length=600), nullable=True),
    sa.Column('renda_mensal', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proprietarios',
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('cpf', sqlmodel.sql.sqltypes.AutoString(length=14), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('telefone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('endereco', sqlmodel.sql.sqltypes.AutoString(length=600), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contratos',
    sa.Column('id_inquilino', sa.Integer(), nullable=False),
    sa.Column('id_imovel', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('valor_aluguel', sa.Float(), nullable=False),
    sa.Column('dia_vencimento', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('observacoes', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_imovel'], ['imoveis.id'], ),
    sa.ForeignKeyConstraint(['id_inquilino'], ['inquilinos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Usando batch_alter_table para compatibilidade com SQLite
    with op.batch_alter_table('imoveis', schema=None) as batch_op:
        batch_op.alter_column('id_proprietario',
                   existing_type=sa.INTEGER(),
                   nullable=True)
    op.execute("UPDATE imoveis SET id_proprietario = NULL")
    with op.batch_alter_table('imoveis', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_imoveis_proprietario', 'proprietarios', ['id_proprietario'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imoveis', schema=None) as batch_op:
        batch_op.drop_constraint('fk_imoveis_proprietario', type_='foreignkey')
        batch_op.alter_column('id_proprietario',
                   existing_type=sa.INTEGER(),
                   nullable=False)
    op.drop_table('contratos')
    op.drop_table('proprietarios')
    op.drop_table('inquilinos')
    # ### end Alembic commands ###
